# Generated by Django 5.1.2 on 2024-12-02 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='Intentos fallidos')),
                ('lock_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_attempt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
